spring:
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/changelog-master.xml
  datasource:
    url: jdbc:mysql://localhost:3309/liquibase
    username: root
    password : 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true